name: Build & Test(.net + Vue)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      #ソース取得
      - name: checkout
        uses: actions/checkout@v4
      
      # .NET セットアップ
      - name: Setup .NET
        run: |
          dotnet restore
          sotnet build --no-restore --configuration Release
      
      #テスト実行
      - name: Test .NET
        run: |
          dotnet test --no-build --configuration Release
      
      #Node セットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            todo-frontend/package-lock.json
            todo-frontend/package.json
      
      #フロント依存関係インストール
      - name: Install frontend dependencies
        working-directory: todo-frontend
        run: npm Install
      
      #フロントエンド
      - name: Build frontend
        working-directory: todo-frontend
        run: npm run build
